program: main.py
name: multi-coil-mri-reddiff-sim
method: bayes
metric:
  goal: maximize
  name: psnr
parameters:
  algorithm.method.observation_weight:
    distribution: log_uniform_values
    min: 1.0e-2
    max: 1.0e+2
  algorithm.method.base_lr:
    distribution: log_uniform_values
    min: 1.0e-4
    max: 1.0
  algorithm.method.base_lambda:
    distribution: log_uniform_values
    min: 1.0e-3
    max: 1.0
  algorithm.method.lambda_scheduling_type:
    values: ["constant", "linear", "sqrt"]

command:
  - ${env}
  - python
  - ${program}
  - problem=multi-coil-mri-knee                             # Set the problem config
  - problem.data.simulated_kspace=True
  - algorithm=reddiff                                # Set the algorithm config
  - pretrain=mri-knee-mvue                          # Set the pre-trained model config
  - wandb=True
  - problem.data.id_list="16,40,68,114,166,199"             # String that indicates the indices of data to use. "0-2" includes 0, 1, and 2. "0,3-4" includes 0, 3, and 4.
  - ${args_no_hyphens}