program: main.py
name: multi-coil-mri-diffpir-real-8x
method: bayes
metric:
  goal: maximize
  name: psnr
parameters:
  algorithm.method.lamb:
    distribution: log_uniform_values
    min: 1.0
    max: 1.0e+5
  algorithm.method.sigma_n:
    distribution: log_uniform_values
    min: 0.01
    max: 1.0e+1
  algorithm.method.xi:
    distribution: log_uniform_values
    min: 1.0e-5
    max: 1.0

command:
  - ${env}
  - python
  - ${program}
  - problem=multi-coil-mri-knee                             # Set the problem config
  - problem.model.acceleration_ratio=8
  - algorithm=diffpir                                # Set the algorithm config
  - pretrain=mri-knee-mvue                          # Set the pre-trained model config
  - wandb=True
  - problem.data.id_list="16,40,68,114,166,199"                    # String that indicates the indices of data to use. "0-2" includes 0, 1, and 2. "0,3-4" includes 0, 3, and 4.
  - ${args_no_hyphens}
