program: main.py
project: SIPBench
name: navier-stokes-dpg
method: bayes
metric:
  goal: minimize
  name: data_fitting_loss
parameters:
  algorithm.method.guidance_scale:
    distribution: log_uniform_values
    min: 0.1
    max: 1000.0
  algorithm.method.num_mc_samples:
    values: [1000, 2000, 3000, 4000, 5000, 6000]

early_terminate:
  type: hyperband
  max_iter: 1000
  eta: 3
  s: 3

command:
  - ${env}
  - python
  - ${program}
  - problem=navier-stokes                          # Set the problem config
  - problem.model.adaptive=False                    # Set the solver's adaptive time stepping to False to avoid too small time steps
  - problem.data.root="../data/navier-stokes-val/Re200.0-t5.0"   # Path to the validation dataset
  - algorithm=dpg                                 # Set the algorithm config
  - pretrain=navier-stokes                          # Set the pre-trained model config
  - wandb=True
  - problem.data.id_list="0-0"                    # String that indicates the indices of data to use. "0-2" includes 0, 1, and 2. "0,3-4" includes 0, 3, and 4.
  - ${args_no_hyphens}