name: CSGMMRI
method:
  _target_: algo.csgm_mri.CSGMMRI
  sigmas_config:
    sigma_dist: geometric
    sigma_begin: 232
    sigma_end: 0.0066
    num_steps: 2311
  start_iter: 1155
  n_steps_each: 3
  step_lr: 3.0e-5
  mse: 0.3

wandb: False
project: CSGMMRI