name: DiffPIR
method:
  _target_: algo.diffpir_gsg.DiffPIR_GSG
  num_steps: 200
  sigma_max: 100
  sigma_min: 0.01
  rho: 7
  sigma_n: 0.05
  lamb: 8.0
  xi: 0.5
  num_queries: 10000
  mu: 0.01
  batch_size: 1000
  is_central: True

wandb: False
project: DiffPIR-GSG
