name: DPS_GSG
method:
  _target_: algo.dps_gsg.DPS_GSG
  diffusion_scheduler_config:
    num_steps: 1000
    schedule: 'linear'
    timestep: 'poly-7'
    scaling: 'none'
  guidance_scale: 0.1
  num_queries: 2048
  batch_size: 512
  mu: 0.01
  is_central: True
  sde: True

