name: EnSGS
method:
  _target_: algo.en_sgs.EnSGS
  guidance_scale: 50.
  num_steps: 30
  num_samples: 1024
  rho_max: 10.0
  rho_min: 0.1
  rho_decay: 0.9
  batch_size: 64
  prior_steps: 25
  likelihood_steps: 300
  resample: True


wandb: False
project: EnSGS
