name: FPS
method:
  _target_: algo.fps.FPS
  scheduler_config:
    num_steps: 100
    sigma_max: 100
    sigma_min: 0.01
    schedule: 'vp'
    timestep: 'vp'
    scaling: 'vp'
  eta: 0.85
  num_particles: 20
