name: MCG-diff
method:
  _target_: algo.mcgdiff.MCG_diff
  scheduler_config:
    num_steps: 200
    sigma_max: 100
    sigma_min: 0.01
    schedule: 'linear'
    timestep: 'poly-7'
    # scaling: 'vp'
  num_particles: 64
