name: ScoreMRI
method:
  _target_: algo.score_mri.ScoreMRI
  scheduler_config:
    num_steps: 2000
    sigma_max: 100
    sigma_min: 0.01
    schedule: vp
    timestep: vp
    scaling: vp
    # schedule: linear
    # timestep: poly-7
  correct_steps: 1
  lr: 0.01
  lamb: 1