name: Unconditional
method:
  _target_: algo.unconditional.UnconditionalDiffusionSampler
  diffusion_scheduler_config:
    num_steps: 1000
    schedule: 'vp'
    timestep: 'vp'
    scaling: 'vp'
  sde: True
