program: main.py
project: SIPBench
name: blackhole-diffpir
method: bayes
metric:
  goal: maximize
  name: psnr
parameters:
  algorithm.method.lamb:
    min: 750000
    max: 1250000
command:
  - ${env}
  - python
  - ${program}
  - problem=blackhole                             # Set the problem config
  - algorithm=diffpir                                # Set the algorithm config
  - pretrain=blackhole                          # Set the pre-trained model config
  - wandb=True
  - problem.data.root="data//blackhole_val/bh_50_synthetic"   # Path to the validation dataset
  - problem.data.id_list="0-4"                    # String that indicates the indices of data to use. "0-2" includes 0, 1, and 2. "0,3-4" includes 0, 3, and 4.
  - ${args_no_hyphens}
