program: main.py
name: inv-scatter-dps
method: bayes
metric:
  goal: maximize
  name: psnr
parameters:
  algorithm.method.guidance_scale:
    min: 1.0
    max: 128.0
    
command:
  - ${env}
  - python
  - ${program}
  - problem=inv-scatter                           # Set the problem config
  - algorithm=dps                                 # Set the algorithm config
  - pretrain=inv-scatter                          # Set the pre-trained model config
  - wandb=True
  - problem.data.root="../data/inv-scatter-val"   # Path to the validation dataset
  - problem.data.id_list="0-2"                    # String that indicates the indices of data to use. "0-2" includes 0, 1, and 2. "0,3-4" includes 0, 3, and 4.
  - ${args_no_hyphens}