program: main.py
project: SipBench
name: fwi-reddiff
method: bayes
metric:
  goal: minimize
  name: data_fitting_loss
parameters:
  algorithm.method.observation_weight:
    distribution: log_uniform_values
    min: 1e-2
    max: 1.0
  algorithm.method.base_lr:
    distribution: log_uniform_values
    min: 1e-3
    max: 1.0
  algorithm.method.base_lambda:
    distribution: log_uniform_values
    min: 1e-3
    max: 1.0
  algorithm.method.lambda_scheduling_type:
    values: ['linear', 'constant', 'sqrt']
early_terminate:
  type: hyperband
  max_iter: 500
  eta: 3
  s: 3

command:
  - ${env}
  - python
  - ${program}
  - problem=fwi                             # Set the problem config
  - algorithm=reddiff                                # Set the algorithm config
  - pretrain=fwi                          # Set the pre-trained model config
  - wandb=True
  - problem.data.root="../data/fwi-val"   # Path to the validation dataset
  - problem.data.id_list="0"                    # String that indicates the indices of data to use. "0-2" includes 0, 1, and 2. "0,3-4" includes 0, 3, and 4.
  - ${args_no_hyphens}
