program: main.py
name: multi-coil-mri-pnpdm-real
method: bayes
metric:
  goal: maximize
  name: psnr
parameters:
  algorithm.method.lgvd_config.lr:
    distribution: log_uniform_values
    min: 1.0e-6
    max: 1.0e-3
  algorithm.method.lgvd_config.tau:
    distribution: log_uniform_values
    min: 1.0e-3
    max: 1.0e-1

command:
  - ${env}
  - python
  - ${program}
  - problem=multi-coil-mri-knee                           # Set the problem config
  - algorithm=pnpdm                                 # Set the algorithm config
  - pretrain=mri-knee-mvue                          # Set the pre-trained model config
  - wandb=True
  - problem.data.id_list="16,40,68,114,166,199"             # String that indicates the indices of data to use. "0-2" includes 0, 1, and 2. "0,3-4" includes 0, 3, and 4.
  - ${args_no_hyphens}